#!/bin/bash
make clean all IIGS=1 SER_DEBUG=1 && cd ../.. && make stpperso-iigs.dsk IIGS=1 && mame apple2gs -window -flop1 stpperso-iigs.dsk -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/stp
