#!/bin/bash
make clean all IIGS=1 && \
  cd ../.. && \
  make IIGS=1 telnet-iigs.dsk && \
  mame apple2gs -window -flop1 telnet-iigs.dsk -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; 
cd src/telnet
