#!/bin/bash
make clean telnet.po && mame apple2gs -window -flop1 telnet.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug
