#!/bin/bash
cp -f ~/.mame/cfg/apple2c0.cfg.115200 ~/.mame/cfg/apple2c0.cfg
make clean all SER_DEBUG=1 && make ammonoid.po && mame apple2gs -window -flop1 ammonoid.po -flop2 ../../disks/qt100.dsk -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug; cd src/ammonoid
