#!/bin/bash
set -e

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "master" ]; then
	echo Not on release branch
	exit 1
fi
rm *.dsk
make clean all dist upload
make clean all dist upload IIGS=1

#Only mastodon and wozamp ported to old II yet
for old in mastodon wozamp; do
	cd src/$old
	make clean all OLDII=1
	cd ../../
	make ${old}-oldii.dsk OLDII=1
done
