#!/bin/bash
set -e

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" != "master" ]; then
	echo Not on release branch
	exit 1
fi
rm -f *.po
make clean all dist upload IIGS=1

#Only mastodon and wozamp ported to old II yet
for old in mastodon wozamp; do
	cd src/$old
	make clean all OLDII=1
	cd ../../
	make ${old}-oldii.po OLDII=1
done

make clean all dist upload

test -d /run/user/1000/gvfs/smb-share\:server\=diskstation.lan\,share\=a2repo/apple2/disks/ || \
	mkdir -p /run/user/1000/gvfs/smb-share\:server\=diskstation.lan\,share\=a2repo/apple2/disks/ && \
	cp *.po /run/user/1000/gvfs/smb-share\:server\=diskstation.lan\,share\=a2repo/apple2/disks/
