#!/bin/bash
ssh a2proxy.lan " \
rm -rf a2tools && \
  git clone https://github.com/colinleroy/a2tools.git && \
  cd a2tools/src && \
  dpkg-buildpackage -us -uc -rfakeroot && \
  cd .. && \
  reprepro --basedir /home/reprepro/debian includedeb bookworm *.deb && \
  reprepro --basedir /home/reprepro/debian includedsc bookworm *.dsc && \
  reprepro-sync"
