#!/bin/bash
make clean all $1 || exit
mame apple2c0 -window -flop1 shufflepuck.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -mouse -debug &
mame apple2c0 -window -flop1 shufflepuck.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2003 -modem null_modem -bitb2 socket.localhost:2002 -mouse -debug &
