HPOSN   :=      $F411   ; Positions the hi-res cursor to (X,Y),A
HPLOT   :=      $F457
HLIN    :=      $F53A   ; Draws a line from the cursor to:
                        ; (A,X) = X-coordinate, and
                        ; (Y) = Y-coordinate.
                        ; Mind that the parameters to both are different
SETHCOL :=      $F6EC   ; Set the hi-res color to (X), where (X)
                        ; must be between 0 and 7.
WHITE   :=      $3
