#!/bin/bash
make clean burgerdisk_utils.po && mame apple2c4 -window -flop1 burgerdisk_utils.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug
