#!/bin/bash
cd bin/65c02
make clean wozampperso-65c02.po && mame apple2gs -window -flop1 wozampperso-65c02.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug 
