#!/bin/bash
make clean all SER_DEBUG=1 && cd ../.. && make wozampperso.po && mame apple2c0 -window -flop1 wozampperso.po -flop2 disks/qt100.dsk -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug; cd src/wozamp
