#!/bin/bash
cd bin/iigs
make clean wozampperso-iigs.po && mame apple2gs -window -flop1 wozampperso-iigs.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug -sound none
