#!/bin/bash
make clean all OLDII=1 && cd ../.. && make wozamp-oldii.dsk OLDII=1 && mame apple2p -window -flop1 wozamp-oldii.dsk -resolution 560x384 -sl2 ssc -sl2:ssc:rs232 null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/wozamp
