#!/bin/bash
make clean sixfortyperso.po && mame apple2c0 -window -flop1 sixfortyperso.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug
