#!/bin/bash
make clean all OLDII=1 SER_DEBUG=1 && cd ../.. && make mastoperso-6502.po OLDII=1 && mame apple2e -window -flop1 mastoperso-6502.po -resolution 560x384 -sl2 ssc -sl2:ssc:rs232 null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/mastodon
