#!/bin/bash
make clean all SER_DEBUG=1 && cd ../.. && make mastoperso.dsk && mame apple2c0 -window -flop1 mastoperso.dsk -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/mastodon
