#!/bin/bash
TYPE="full"
if [ "$1" != "" ]; then
  TYPE=$1
fi
make clean all DEBUG_HD=$TYPE && \
  make imageviewer.po && mame apple2gs -window -flop1 imageviewer.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug -sl7 scsi -hard disks/smart0.po -sound none; cd src/image-viewer
