#!/bin/bash
FLOP2="-flop2 disks/qt100.dsk"
make clean all IIGS=1 && cd ../.. && make imageviewer.dsk && mame apple2gs -window -flop1 imageviewer.dsk $FLOP2 -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/image-viewer
