#!/bin/bash
make clean all IIGS=1 SER_DEBUG=1 && cd ../.. && make glider.po IIGS=1 && mame apple2gs -window -flop1 glider.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -mouse -debug; cd src/mastodon
