#!/bin/bash
make clean all && mame apple2c0 -window -flop1 bin/en/glider-en.po -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -mouse -debug
