#!/bin/bash
make clean all SER_DEBUG=1 && cd ../.. && make glider.po && mame apple2ee -window -flop1 glider.po -resolution 560x384 -sl1 ssc -sl1:ssc:rs232 null_modem -bitb socket.localhost:2001 -sl2 ssc -sl2:ssc:rs232 null_modem -bitb2 socket.localhost:2000 -sl4 ssc -debug; cd src/glider
