;
; File generated by cc65 v 2.19 - Git 547d92358
;
	.fopt		compiler,"cc65 v 2.19 - Git 547d92358"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_ntohs
	.import		___errno
	.import		_sprintf
	.import		_strcpy
	.import		_strlen
	.import		_memcpy
	.import		_bzero
	.import		_write
	.import		_lseek
	.import		_sleep
	.import		_platform_msleep
	.import		_gotoy
	.import		_gotoxy
	.import		_wherey
	.import		_cputs
	.import		_cprintf
	.import		_progress_bar
	.import		_ser_params
	.import		_simple_serial_set_speed
	.import		_simple_serial_set_parity
	.import		_simple_serial_dtr_onoff
	.import		_simple_serial_slot_dtr_onoff
	.import		_simple_serial_read_no_irq
	.import		_serial_putc_direct
	.import		_simple_serial_write
	.import		_buffer
	.import		_serial_model
	.import		_is_iigs
	.import		_qt1x0_thumb_histogram
	.import		_qt1x0_load_thumb_data
	.export		_qt1x0_callbacks
	.import		_scrw
	.export		_is_qt100

.segment	"DATA"

.segment	"QT1X0"
_qt1x0_callbacks:
	.word	$00FF
	.addr	_qt1x0_wakeup
	.addr	_qt1x0_set_speed
	.addr	_qt1x0_set_camera_name
	.addr	_qt1x0_set_camera_time
	.addr	_qt1x0_get_information
	.addr	_qt1x0_set_quality
	.addr	_qt1x0_set_flash
	.addr	_qt1x0_take_picture
	.addr	_qt1x0_get_picture
	.addr	_qt1x0_get_thumbnail
	.addr	_qt1x0_delete_pictures
	.addr	_qt1x0_get_filename
	.addr	_qt1x0_thumb_histogram
	.addr	_qt1x0_load_thumb_data

.segment	"RODATA"

.segment	"QT1X0"
S0052:
	.byte	$20,$20,$57,$69,$64,$74,$68,$20,$25,$75,$2C,$20,$68,$65,$69,$67
	.byte	$68,$74,$20,$25,$75,$2C,$20,$25,$6C,$75,$20,$62,$79,$74,$65,$73
	.byte	$20,$28,$25,$73,$29,$0D,$0A,$00
S004D:
	.byte	$53,$70,$65,$65,$64,$20,$73,$65,$74,$20,$63,$6F,$6D,$6D,$61,$6E
	.byte	$64,$20,$66,$61,$69,$6C,$65,$64,$2E,$0D,$0A,$00
S0055:
	.byte	$20,$20,$47,$65,$74,$74,$69,$6E,$67,$20,$74,$68,$75,$6D,$62,$6E
	.byte	$61,$69,$6C,$20,$25,$64,$2E,$2E,$2E,$0D,$0A,$00
S004A:
	.byte	$50,$69,$6E,$67,$69,$6E,$67,$20,$51,$75,$69,$63,$6B,$54,$61,$6B
	.byte	$65,$20,$31,$78,$30,$2E,$2E,$2E,$20,$00
S0056:
	.byte	$47,$65,$74,$74,$69,$6E,$67,$20,$69,$6E,$66,$6F,$72,$6D,$61,$74
	.byte	$69,$6F,$6E,$2E,$2E,$2E,$0D,$0A,$00
S0053:
	.byte	$20,$20,$47,$65,$74,$74,$69,$6E,$67,$20,$70,$69,$63,$74,$75,$72
	.byte	$65,$2E,$2E,$2E,$0D,$0A,$00
S004F:
	.byte	$20,$20,$47,$65,$74,$74,$69,$6E,$67,$20,$68,$65,$61,$64,$65,$72
	.byte	$2E,$2E,$2E,$0D,$0A,$00
S0054	:=	S004F+0
S004C:
	.byte	$55,$70,$67,$72,$61,$64,$69,$6E,$67,$20,$73,$70,$65,$65,$64,$2E
	.byte	$2E,$2E,$0D,$0A,$00
S004E:
	.byte	$20,$20,$47,$65,$74,$74,$69,$6E,$67,$20,$64,$61,$74,$61,$2E,$2E
	.byte	$2E,$0D,$0A,$00
S0049:
	.byte	$45,$72,$72,$6F,$72,$20,$28,$24,$25,$30,$32,$58,$29,$2E,$0D,$0A
	.byte	$00
S0043:
	.byte	$25,$73,$25,$73,$49,$4D,$41,$47,$45,$25,$64,$2E,$51,$54,$4B,$00
S0048:
	.byte	$54,$69,$6D,$65,$6F,$75,$74,$2E,$20,$00
S0047	:=	S0048+0
S004B:
	.byte	$44,$6F,$6E,$65,$2E,$20,$00
S0050:
	.byte	$71,$6B,$74,$6E,$00
S0051:
	.byte	$71,$6B,$74,$6B,$00
S0045:
	.byte	$2F,$00
S0044	:=	S0052+39
S0046	:=	S0052+39

.segment	"BSS"

_is_qt100:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_wakeup (unsigned char speed)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_wakeup: near

.segment	"QT1X0"

	jsr     pusha
	lda     #<(S004A)
	ldx     #>(S004A)
	jsr     _cputs
	lda     _is_iigs
	bne     L0002
	lda     _ser_params+3
	jsr     pusha
	lda     #$01
	jsr     _simple_serial_slot_dtr_onoff
	ldx     #$00
	lda     #$01
	jsr     _sleep
	lda     _ser_params+3
	jsr     pusha
	lda     #$00
	jsr     _simple_serial_slot_dtr_onoff
	jmp     L0003
L0002:	lda     #$00
	jsr     _simple_serial_dtr_onoff
L0003:	jsr     _get_hello
	sta     M0001
	cmp     #$00
	bne     L0004
	lda     _is_iigs
	beq     L0005
	lda     #$01
	jsr     _simple_serial_dtr_onoff
L0005:	ldx     #$00
	txa
	jmp     incsp1
L0004:	lda     M0001
	cmp     #$01
	jsr     booleq
	sta     _is_qt100
	ldy     #$00
	lda     (c_sp),y
	cmp     #$12
	bne     L000E
	lda     _is_iigs
	beq     L000A
	lda     #$11
	jmp     L000C
L000A:	lda     #$0F
L000C:	sta     (c_sp),y
L000E:	lda     (c_sp),y
	jsr     _send_hello
	cmp     #$00
	beq     L0009
	ldx     #$00
	txa
	jmp     incsp1
L0009:	tax
	lda     #$02
	jsr     _simple_serial_set_parity
	lda     #<(S004B)
	ldx     #>(S004B)
	jsr     _cputs
	ldx     #$00
	lda     M0001
	jmp     incsp1

.segment	"QT1X0"

M0001:
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_set_speed (unsigned char speed)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_set_speed: near

.segment	"QT1X0"

	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _sleep
	ldy     #$00
	lda     (c_sp),y
	cmp     #$12
	bne     L0014
	lda     _is_iigs
	beq     L0010
	lda     #$11
	jmp     L0012
L0010:	lda     #$0F
L0012:	sta     (c_sp),y
L0014:	lda     (c_sp),y
	cmp     #$0E
	beq     L0017
	cmp     #$0F
	beq     L0015
	cmp     #$11
	beq     L0016
	jmp     L0017
L0015:	lda     #$10
	sta     M0001+13
	jmp     L0006
L0016:	lda     #$30
	sta     M0001+13
	jmp     L0006
L0017:	jsr     push0
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _send_command
	jmp     incsp1
L0006:	lda     #<(S004C)
	ldx     #>(S004C)
	jsr     _cputs
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$10
	jsr     _simple_serial_write
	lda     #$05
	jsr     _get_ack
	cmp     #$00
	beq     L000B
	lda     #<(S004D)
	ldx     #>(S004D)
	jsr     _cputs
	ldx     #$00
	lda     #$FF
	jmp     incsp1
L000B:	jsr     _send_ack
	ldx     #$00
	lda     #$C8
	jsr     _platform_msleep
	ldx     #$00
	lda     (c_sp,x)
	jsr     _simple_serial_set_speed
L000C:	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$01
	lda     #$00
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L000C
	cmp     #$FF
	bne     L000C
	jsr     _send_ack
	lda     #$05
	jsr     _get_ack
	jmp     incsp1

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$2A
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$05
	.byte	$00
	.byte	$03
	.byte	$03
	.byte	$08
	.byte	$04
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_set_camera_name (const char *name)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_set_camera_name: near

.segment	"QT1X0"

	jsr     pushax
	ldy     #$2C
L0002:	lda     M0002,y
	sta     M0001,y
	dey
	bpl     L0002
	jsr     ldax0sp
	jsr     _strlen
	sta     M0003
	cmp     #$20
	bcc     L0003
	lda     #$1F
	sta     M0003
L0003:	lda     #<(M0001+13)
	ldx     #>(M0001+13)
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     M0003
	jsr     _memcpy
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$2D
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$05
	jsr     _send_command
	jmp     incsp2

.segment	"QT1X0"

M0002:
	.byte	$16
	.byte	$2A
	.byte	$00
	.byte	$02
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$22
	.byte	$00
	.byte	$02
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20

.segment	"BSS"

M0001:
	.res	45,$00
M0003:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_set_camera_time (unsigned char day, unsigned char month, unsigned char year, unsigned char hour, unsigned char minute, unsigned char second)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_set_camera_time: near

.segment	"QT1X0"

	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	sta     M0001+14
	dey
	lda     (c_sp),y
	sta     M0001+13
	dey
	lda     (c_sp),y
	sta     M0001+15
	dey
	lda     (c_sp),y
	sta     M0001+16
	dey
	lda     (c_sp),y
	sta     M0001+17
	dey
	lda     (c_sp),y
	sta     M0001+18
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$13
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$05
	jsr     _send_command
	jmp     incsp6

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$2A
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$08
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_get_information (struct _camera_info *info)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_get_information: near

.segment	"QT1X0"

	jsr     pushax
	lda     #<(S0056)
	ldx     #>(S0056)
	jsr     _cputs
	lda     #$00
	jsr     pusha
	lda     #$30
	jsr     pusha
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$80
	ldx     #$00
	jsr     _send_photo_data_command
	cmp     #$00
	beq     L0002
	ldx     #$00
	lda     #$0B
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp2
L0002:	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$80
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0003
	cmp     #$FF
	bne     L0003
	inx
	lda     #$06
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp2
L0003:	jsr     ldptr10sp
	lda     _buffer+4
	ldy     #$00
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+6
	ldy     #$01
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+27
	ldy     #$02
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+22
	ldy     #$03
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+2
	ldy     #$04
	sta     (ptr1),y
	lda     _buffer+2
	cmp     #$65
	bcc     L0005
	jsr     ldptr10sp
	lda     _buffer+2
	lsr     a
	ldy     #$04
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     #$01
	jmp     L0010
L0005:	jsr     ldptr10sp
	lda     _buffer+2
	ldy     #$04
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     #$00
L0010:	ldy     #$05
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+17
	ldy     #$29
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+16
	ldy     #$28
	sta     (ptr1),y
	jsr     ldptr10sp
	ldx     #$07
	lda     #$D0
	clc
	adc     _buffer+18
	bcc     L000D
	inx
L000D:	ldy     #$26
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+19
	ldy     #$2A
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+20
	ldy     #$2B
	sta     (ptr1),y
	lda     #$1F
	sta     M0001
L0007:	lda     M0001
	beq     L0008
	ldy     M0001
	lda     _buffer+47,y
	cmp     #$20
	beq     L000F
	inc     M0001
	lda     M0001
	clc
	adc     #<(_buffer+47)
	sta     ptr1
	lda     #$00
	adc     #>(_buffer+47)
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jmp     L0008
L000F:	dec     M0001
	jmp     L0007
L0008:	jsr     ldax0sp
	jsr     incax6
	jsr     pushax
	lda     #<(_buffer+47)
	ldx     #>(_buffer+47)
	jsr     _strcpy
	ldx     #$00
	txa
	jmp     incsp2

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_set_quality (unsigned char quality)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_set_quality: near

.segment	"QT1X0"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$10
	beq     L0005
	lda     #$20
L0005:	sta     M0001+13
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$0F
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$05
	jsr     _send_command
	jmp     incsp1

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$2A
	.byte	$00
	.byte	$06
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$06
	.byte	$02
	.byte	$10
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_set_flash (unsigned char mode)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_set_flash: near

.segment	"QT1X0"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	sta     M0001+13
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$0E
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$05
	jsr     _send_command
	jmp     incsp1

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$2A
	.byte	$00
	.byte	$07
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$00
	.byte	$07
	.byte	$01
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_take_picture (void)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_take_picture: near

.segment	"QT1X0"

	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$07
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$14
	jmp     _send_command

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$1B
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_get_picture (unsigned char n_pic, int fd, long avail)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_get_picture: near

.segment	"QT1X0"

	jsr     pusheax
	ldx     #$00
	lda     #$01
	jsr     _sleep
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$02
	lda     #$00
	jsr     _bzero
	jsr     _wherey
	sta     M0004
	lda     #<(S004F)
	ldx     #>(S004F)
	jsr     _cputs
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	lda     #$21
	jsr     pusha
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$40
	ldx     #$00
	jsr     _send_photo_data_command
	cmp     #$00
	beq     L0002
	ldx     #$00
	lda     #$0B
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp7
L0002:	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$40
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0003
	cmp     #$FF
	bne     L0003
	inx
	lda     #$06
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp7
L0003:	lda     _buffer+7
	sta     M0003
	lda     _buffer+6
	sta     M0003+1
	lda     _buffer+5
	sta     M0003+2
	lda     #$00
	sta     M0003+3
	sta     sreg+1
	lda     M0003+2
	sta     sreg
	ldx     M0003+1
	lda     M0003
	jsr     pusheax
	ldy     #$07
	jsr     ldeaxysp
	jsr     tosugteax
	beq     L0005
	ldx     #$00
	lda     #$08
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp7
L0005:	lda     _buffer+8
	sta     M0001
	lda     _buffer+9
	sta     M0001+1
	lda     _buffer+10
	sta     M0002
	lda     _buffer+11
	sta     M0002+1
	lda     #>(S0050)
	sta     M0005+1
	lda     #<(S0050)
	sta     M0005
	lda     _serial_model
	cmp     #$01
	bne     L0006
	lda     #>(S0051)
	sta     M0005+1
	lda     #<(S0051)
	sta     M0005
L0006:	lda     #<(_buffer+14)
	ldx     #>(_buffer+14)
	jsr     pushax
	lda     #<(_buffer+4)
	ldx     #>(_buffer+4)
	jsr     pushax
	ldx     #$00
	lda     #$3C
	jsr     _memcpy
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     _memcpy
	lda     #<(_buffer+4)
	ldx     #>(_buffer+4)
	jsr     pushax
	lda     #<(M0006)
	ldx     #>(M0006)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _memcpy
	lda     #<(_buffer+544)
	ldx     #>(_buffer+544)
	jsr     pushax
	lda     #<(M0002)
	ldx     #>(M0002)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _memcpy
	lda     #<(_buffer+546)
	ldx     #>(_buffer+546)
	jsr     pushax
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     _memcpy
	ldy     #$07
	jsr     pushwysp
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$08
	lda     #$00
	jsr     _write
	ldy     #$07
	jsr     pushwysp
	lda     #$E0
	ldx     #$02
	jsr     push0ax
	ldx     #$00
	lda     #$02
	jsr     _lseek
	lda     #<(S0052)
	ldx     #>(S0052)
	jsr     pushax
	lda     M0001
	ldx     M0001+1
	jsr     _ntohs
	jsr     pushax
	lda     M0002
	ldx     M0002+1
	jsr     _ntohs
	jsr     pushax
	lda     M0003+3
	sta     sreg+1
	lda     M0003+2
	sta     sreg
	ldx     M0003+1
	lda     M0003
	jsr     pusheax
	lda     M0005
	ldx     M0005+1
	jsr     pushax
	ldy     #$0C
	jsr     _cprintf
	lda     #$00
	jsr     pusha
	lda     M0004
	jsr     _gotoxy
	lda     #<(S0053)
	ldx     #>(S0053)
	jsr     _cputs
	lda     M0004
	clc
	adc     #$02
	jsr     _gotoy
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha
	lda     #$10
	jsr     pusha
	lda     M0003+3
	sta     sreg+1
	lda     M0003+2
	sta     sreg
	ldx     M0003+1
	lda     M0003
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     _receive_data
	jmp     incsp7

.segment	"QT1X0"

M0006:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$00
	.byte	$00
	.byte	$73
	.byte	$E4
	.byte	$00
	.byte	$01

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	4,$00
M0004:
	.res	1,$00
M0005:
	.res	2,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_get_thumbnail (unsigned char n_pic, int fd, struct _thumb_info *info)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_get_thumbnail: near

.segment	"QT1X0"

	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     _sleep
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$02
	lda     #$00
	jsr     _bzero
	jsr     _wherey
	sta     M0001
	lda     #<(S0054)
	ldx     #>(S0054)
	jsr     _cputs
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	lda     #$21
	jsr     pusha
	lda     #$00
	sta     sreg+1
	sta     sreg
	lda     #$40
	ldx     #$00
	jsr     _send_photo_data_command
	cmp     #$00
	beq     L0002
	ldx     #$00
	lda     #$0B
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp5
L0002:	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$40
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0003
	cmp     #$FF
	bne     L0003
	inx
	lda     #$06
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp5
L0003:	ldy     #$01
	lda     (c_sp),y
	dey
	ora     (c_sp),y
	beq     L0007
	jsr     ldptr10sp
	lda     _buffer+24
	ldy     #$00
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+19
	ldy     #$01
	sta     (ptr1),y
	jsr     ldptr10sp
	ldx     #$07
	lda     #$D0
	clc
	adc     _buffer+15
	bcc     L0006
	inx
L0006:	ldy     #$02
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+13
	ldy     #$04
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+14
	ldy     #$05
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+16
	ldy     #$06
	sta     (ptr1),y
	jsr     ldptr10sp
	lda     _buffer+17
	ldy     #$07
	sta     (ptr1),y
	lda     #$00
L0007:	jsr     pusha
	lda     M0001
	jsr     _gotoxy
	lda     #<(S0055)
	ldx     #>(S0055)
	jsr     pushax
	ldy     #$06
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
	ldy     #$04
	lda     (c_sp),y
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$60
	ldx     #$09
	jsr     push0ax
	ldy     #$09
	jsr     ldaxysp
	jsr     _receive_data
	jmp     incsp5

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ qt1x0_delete_pictures (void)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_delete_pictures: near

.segment	"QT1X0"

	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$3C
	jmp     _send_command

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$29
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.endproc

; ---------------------------------------------------------------
; void __near__ qt1x0_get_filename (unsigned char n_pic, char *dirname, char *filename)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_qt1x0_get_filename: near

.segment	"QT1X0"

	jsr     pushax
	jsr     pushw0sp
	lda     #<(S0043)
	ldx     #>(S0043)
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	txa
	beq     L0002
	ldy     #$07
	jsr     ldaxysp
	jmp     L0003
L0002:	lda     #<(S0044)
	ldx     #>(S0044)
L0003:	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	txa
	beq     L0004
	lda     #<(S0045)
	ldx     #>(S0045)
	jmp     L0005
L0004:	lda     #<(S0046)
	ldx     #>(S0046)
L0005:	jsr     pushax
	ldy     #$0C
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$0A
	jsr     _sprintf
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ get_ack (unsigned char wait)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_get_ack: near

.segment	"QT1X0"

	jsr     pusha
	jmp     L0005
L0002:	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     _simple_serial_read_no_irq
	cpx     #$00
	bne     L0005
	cmp     #$00
	bne     L0005
	lda     M0001
	beq     L0001
L0005:	ldy     #$00
	lda     (c_sp),y
	php
	lda     (c_sp),y
	sec
	sbc     #$01
	sta     (c_sp),y
	plp
	bne     L0002
	ldx     #$00
	lda     #$FF
L0001:	jmp     incsp1

.segment	"BSS"

M0001:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; void __near__ send_ack (void)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_send_ack: near

.segment	"QT1X0"

	lda     #$06
	jmp     _serial_putc_direct

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ send_command (const char *cmd, unsigned char len, unsigned char ping, unsigned char s_ack, unsigned char wait)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_send_command: near

.segment	"QT1X0"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	beq     L0003
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     _simple_serial_write
	lda     #$05
	jsr     _get_ack
	cmp     #$00
	beq     L0003
	ldx     #$00
	lda     #$FF
	jmp     incsp6
L0003:	ldy     #$03
	lda     (c_sp),y
	bne     L0004
	tax
	jmp     incsp6
L0004:	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	ldx     #$00
	lda     (c_sp),y
	jsr     _simple_serial_write
	ldy     #$00
	lda     (c_sp),y
	jsr     _get_ack
	cmp     #$00
	beq     L0005
	ldx     #$00
	lda     #$FF
	jmp     incsp6
L0005:	ldy     #$01
	lda     (c_sp),y
	beq     L0006
	jsr     _send_ack
L0006:	ldx     #$00
	txa
	jmp     incsp6

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ get_hello (void)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_get_hello: near

.segment	"QT1X0"

	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0002
	cmp     #$FF
	bne     L0002
	lda     #<(S0047)
	ldx     #>(S0047)
	jsr     _cputs
	ldx     #$00
	txa
	rts
L0002:	lda     _buffer
	cmp     #$A5
	beq     L0007
	ldx     #$00
	txa
	rts
L0007:	lda     _buffer+3
	cmp     #$C8
	bne     L0008
	ldx     #$00
	lda     #$02
	rts
L0008:	lda     #$01
	ldx     #$00
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ send_hello (unsigned char speed)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_send_hello: near

.segment	"QT1X0"

	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$0F
	bne     L000D
	lda     #$4B
	jmp     L0012
L000D:	lda     #$E1
L0012:	sta     M0001+6
	tya
	sta     M0001+7
	sta     M0003
	sta     M0002
L000E:	lda     M0003
	cmp     #$0C
	bcs     L000F
	ldy     M0003
	lda     M0001,y
	clc
	adc     M0002
	sta     M0002
	inc     M0003
	jmp     L000E
L000F:	lda     M0002
	sta     M0001+12
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	ldx     #$00
	lda     #$0D
	jsr     _simple_serial_write
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0009
	cmp     #$FF
	bne     L0009
	lda     #<(S0048)
	ldx     #>(S0048)
	jsr     _cputs
	jmp     L0014
L0009:	ldx     #$00
	lda     _buffer
	beq     L0001
	lda     #<(S0049)
	ldx     #>(S0049)
	jsr     pushax
	lda     M0003
	jsr     pusha0
	ldy     #$04
	jsr     _cprintf
L0014:	ldx     #$00
	lda     #$FF
L0001:	jmp     incsp1

.segment	"QT1X0"

M0001:
	.byte	$5A
	.byte	$A5
	.byte	$55
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$25
	.byte	$80
	.byte	$00
	.byte	$80
	.byte	$02
	.byte	$00
	.byte	$FF

.segment	"BSS"

M0002:
	.res	1,$00
M0003:
	.res	1,$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ send_photo_data_command (unsigned char pnum, unsigned char format, unsigned long picture_size)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_send_photo_data_command: near

.segment	"QT1X0"

	jsr     pusheax
	ldy     #$05
	lda     (c_sp),y
	sta     M0001+6
	dey
	lda     (c_sp),y
	sta     M0001+3
	jsr     ldeax0sp
	lda     sreg
	sta     M0001+7
	jsr     ldeax0sp
	stx     M0001+8
	jsr     ldeax0sp
	sta     M0001+9
	lda     #<(M0001)
	ldx     #>(M0001)
	jsr     pushax
	lda     #$0B
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     pusha
	lda     #$05
	jsr     _send_command
	jmp     incsp6

.segment	"QT1X0"

M0001:
	.byte	$16
	.byte	$28
	.byte	$00
	.byte	$10
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$00
	.byte	$70
	.byte	$80
	.byte	$00

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ receive_data (unsigned char n_pic, unsigned char type, unsigned long size, int fd)
; ---------------------------------------------------------------

.segment	"QT1X0"

.proc	_receive_data: near

.segment	"QT1X0"

	jsr     pushax
	jsr     _wherey
	sta     M0001
	lda     #$00
	sta     M0003
	ldy     #$05
	jsr     ldeaxysp
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	ldy     #$00
	sty     sreg+1
	jsr     shreax1
	sta     M0004
	stx     M0004+1
	ldy     #$05
	jsr     ldeaxysp
	jsr     pusheax
	lda     #$FF
	ldx     #$01
	jsr     tosand0ax
	sta     M0005
	stx     M0005+1
	lda     #<(S004E)
	ldx     #>(S004E)
	jsr     _cputs
	lda     #$02
	jsr     pusha
	lda     M0001
	jsr     pusha
	lda     _scrw
	sec
	sbc     #$02
	jsr     pusha
	jsr     pushl0
	lda     M0004
	ldx     M0004+1
	jsr     axulong
	jsr     _progress_bar
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	ldy     #$07
	lda     (c_sp),y
	jsr     pusha
	ldy     #$07
	jsr     ldeaxysp
	jsr     _send_photo_data_command
	lda     #$00
	sta     M0002
	sta     M0002+1
L0003:	lda     M0002
	cmp     M0004
	lda     M0002+1
	sbc     M0004+1
	jcs     L0004
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$02
	lda     #$00
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L0008
	cmp     #$FF
	bne     L0008
	inx
	lda     #$06
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp8
L0008:	jsr     pushw0sp
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldx     #$02
	lda     #$00
	jsr     _write
	cmp     #$00
	txa
	sbc     #$02
	bvc     L000B
	eor     #$80
L000B:	bpl     L000A
	lda     #$FF
	sta     M0003
	ldx     #$00
	lda     #$0B
	sta     ___errno
	stx     ___errno+1
L000A:	lda     #$FF
	jsr     pusha
	jsr     pusha
	lda     _scrw
	sec
	sbc     #$02
	jsr     pusha
	lda     M0002
	ldx     M0002+1
	jsr     axulong
	jsr     pusheax
	lda     M0004
	ldx     M0004+1
	jsr     axulong
	jsr     _progress_bar
	jsr     _send_ack
	inc     M0002
	jne     L0003
	inc     M0002+1
	jmp     L0003
L0004:	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     _simple_serial_read_no_irq
	cpx     #$FF
	bne     L000C
	cmp     #$FF
	bne     L000C
	inx
	lda     #$06
	sta     ___errno
	stx     ___errno+1
	lda     #$FF
	jmp     incsp8
L000C:	jsr     pushw0sp
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	lda     M0005
	ldx     M0005+1
	jsr     _write
	cmp     M0005
	txa
	sbc     M0005+1
	bcs     L000E
	lda     #$FF
	sta     M0003
	ldx     #$00
	lda     #$0B
	sta     ___errno
	stx     ___errno+1
L000E:	lda     #$FF
	jsr     pusha
	jsr     pusha
	lda     _scrw
	sec
	sbc     #$02
	jsr     pusha
	lda     #$64
	ldx     #$00
	jsr     push0ax
	jsr     _progress_bar
	ldx     #$00
	lda     M0003
	jmp     incsp8

.segment	"BSS"

M0001:
	.res	1,$00
M0002:
	.res	2,$00
M0003:
	.res	1,$00
M0004:
	.res	2,$00
M0005:
	.res	2,$00

.endproc

