#!/bin/bash
TYPE="full"
TYPE=$1
FLOPNAME="thumb"
FLOP2="-flop2 ../../disks/thumb.po"

TESTFILE=TEST$1.$EXT
if [ "$2" != "" ]; then
  TESTFILE=$2
  [ -f ../../disks/$FLOPNAME.po ] || java -jar ../../bin/ac.jar -pro140 ../../disks/$FLOPNAME.po QTTEST
  java -jar ../../bin/ac.jar -d ../../disks/$FLOPNAME.po THUMB
  
  echo "Putting $TESTFILE as TEST$1.$EXT into $FLOPNAME.po"
  java -jar ../../bin/ac.jar -p ../../disks/$FLOPNAME.po \
    THUMB BIN '$2000' < "$TESTFILE"
fi

make clean all DEBUG_THUMB=$TYPE && mame apple2c0 -window -flop1 quicktake.po $FLOP2 -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug
