#!/bin/bash
make clean all IIGS=1 && cd ../.. && make quicktake.dsk && mame apple2gs -window -flop1 quicktake.dsk -flop2 disks/qt150.dsk -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/quicktake
