#!/bin/bash
make clean all && cd ../.. && make quicktake.dsk && mame apple2gs -window -flop1 quicktake.dsk -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -nodebug; cd src/quicktake
