#!/bin/bash
FLOP2="-flop2 disks/qt200.dsk"
make clean all IIGS=1 && cd ../.. && make quicktake.dsk && mame apple2gs -window -flop1 quicktake.dsk $FLOP2 -resolution 560x384 -modem null_modem -bitb socket.localhost:2000 -nomouse -debug; cd src/quicktake
