#!/bin/bash
TYPE="full"
if [ "$1" != "" ]; then
  TYPE=$1
  if [ "$TYPE" != "50" ]; then
    FLOPNAME="qt$1"
	  FLOP2="-flop2 ../../disks/qt$1.dsk"
  else
    FLOPNAME="dc50"
    FLOP2="-flop2 ../../disks/dc50.dsk"
  fi
else
  FLOPNAME="qt100"
	FLOP2="-flop2 ../../disks/qt100.dsk"
fi

if [ "$1" = "200" ]; then
  EXT=JPG
elif [ "$1" = "50" ]; then
  EXT=KDC
else
  EXT=QTK
fi

TESTFILE=TEST$1.$EXT
if [ "$2" != "" ]; then
  TESTFILE=$2
  java -jar ../../bin/ac.jar -d ../../disks/$FLOPNAME.dsk TEST$1.$EXT
  
  echo "Putting $TESTFILE as TEST$1.$EXT into $FLOPNAME.dsk"
  java -jar ../../bin/ac.jar -p ../../disks/$FLOPNAME.dsk \
    TEST$1.$EXT BIN '$2000' < "$TESTFILE"
fi

make clean all DEBUG_FLOPPY=$TYPE && mame apple2cp -window -flop1 quicktake.po $FLOP2 -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -debug
