#!/bin/bash
make clean all && cd ../.. && make quicktake.dsk && mame apple2c0 -window -flop1 quicktake.dsk -resolution 560x384 -printer null_modem -bitb socket.localhost:2001 -modem null_modem -bitb2 socket.localhost:2000 -nomouse -nodebug; cd src/quicktake
