;
; File generated by cc65 v 2.19 - Git 54a2410b5
;
	.fopt		compiler,"cc65 v 2.19 - Git 54a2410b5"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     M0001
	clc
	adc     M0002
	sta     M0002
	lda     M0001+1
	adc     M0002+1
	sta     M0002+1
	lda     M0001
	ldx     M0001+1
	jsr     negax
	clc
	adc     M0003
	sta     M0003
	txa
	adc     M0003+1
	sta     M0003+1
	rts

.segment	"BSS"

M0001:
	.res	2,$00
M0002:
	.res	2,$00
M0003:
	.res	2,$00

.endproc

